services:
  kea4:
    image: docker.cloudsmith.io/isc/docker/kea-dhcp4:2.5.2
    container_name: kea4
    volumes:
      - ./kea/config:/etc/kea
      - ./kea/leases:/var/lib/kea
    network_mode: "host"
    restart: unless-stopped

  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    network_mode: bridge
    environment:
      - MENU_VERSION=2.0.84 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    volumes:
      - ./netboot/config:/config # optional
      - ./netboot/assets:/assets # optional
    ports:
      - 3001:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8080:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_share
    volumes:
      - ./scripts:/usr/share/nginx/html:ro
    ports:
      - 8081:80
    restart: unless-stopped